spring:
  application:
    name: openjobs-insightful
insightful:
  api:
    base-url: https://app.insightful.io/api/v1
    key: 

resilience4j:
  retry:
    instances:
      insightfulSharedSettings:
        max-attempts: 3
        wait-duration: 500ms
        retry-exceptions:
          - feign.FeignException
  circuitbreaker:
    instances:
      insightfulSharedSettings:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
