spring:
  application:
    name: openjobs-insightful
insightful:
  api:
    base-url: https://app.insightful.io/api/v1
    key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Inc1cGowb210X3NxODZ2ciIsImFjY291bnRJZCI6IndvY2J6dnp3b2s0c2RxayIsIm9yZ2FuaXphdGlvbklkIjoid3RhMWltNGdhcmRmejZiIiwidHlwZSI6InVzZXIiLCJ1c2VyVHlwZSI6ImFwaSIsInZlcnNpb24iOjIsImlhdCI6MTc2NDQyNDg3NywiZXhwIjozMTczMDg4NjcyNzcsImF1ZCI6WyJQUk9EIl0sImlzcyI6IlBST0QifQ.nWwZ2V6saSeC1R3pGHS9wIGuIyb1oe6JTrBjhgw-8ec

#    key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ind3Z2YwMTlwZHdwNm9wYyIsImFjY291bnRJZCI6Indoc3pjZ2x0a2FjNm52byIsIm9yZ2FuaXphdGlvbklkIjoid3l5MDh4Mnpndnh6Zm96IiwidHlwZSI6InVzZXIiLCJ1c2VyVHlwZSI6ImFwaSIsInZlcnNpb24iOjIsImlhdCI6MTc2MzcwMjcwNSwiZXhwIjozMTczMDgxNDUxMDUsImF1ZCI6WyJQUk9EIl0sImlzcyI6IlBST0QifQ.JO2tcCngXoZDdOUHYKTs6BQ26IzMPlxy9tYuRY1HHrE
#    key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IndzenN0enpiZXh1bXd4ZiIsImFjY291bnRJZCI6Ind5ZmhmNnlleHBoZ3N3YiIsIm9yZ2FuaXphdGlvbklkIjoid284YTc5bl93OG5jdWxoIiwidHlwZSI6InVzZXIiLCJ1c2VyVHlwZSI6ImFwaSIsInZlcnNpb24iOjIsImlhdCI6MTc2MzI3MTQ2NywiZXhwIjozMTczMDc3MTM4NjcsImF1ZCI6WyJQUk9EIl0sImlzcyI6IlBST0QifQ.Z04U6faJVNlwbflkr8v4aekRdKDx3mmKU4o3yMydXFE

resilience4j:
  retry:
    instances:
      insightfulSharedSettings:
        max-attempts: 3
        wait-duration: 500ms
        retry-exceptions:
          - feign.FeignException
  circuitbreaker:
    instances:
      insightfulSharedSettings:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
